### ISSUE TITLE
Suggestion: Use XoshiroPRNG.Net instead of inlined Mersenne Twister code

### ISSUE THREAD

**Issue by pepoluan** [Sakorona/SDVMods#100]
Several concerns, in no particular order:
- The licensing of the code in `TwilightCoreShared/PRNG/MersenneTwister.cs` is ... complicated. XoshiroPRNG.Net is _very_ permissively licensed
- The Xoshiro PRNG family is faster than Mersenne Twister. [Here's a comparison.](https://prng.di.unimi.it/#quality)
- Mersenne Twister itself [has many drawbacks](https://en.wikipedia.org/wiki/Mersenne_Twister#Disadvantages)
- I personally keep XoshiroPRNG.Net up-to-date. The most recent update was released on 2021-05-07, where I implemented a corrected algorithm from upstream

In fact, [**here's an article**](https://www.codeproject.com/Articles/1083372/Random-Number-Generator-Recommendations-for-Applic) (not written by me) that was also kind of negative about Mersenne Twister, and it actually (to my surprise!) recommended XoshiroPRNG.Net for .Net applications.

I am quite confident of XoshiroPRNG.Net's performance and quality, so much so that I've released a mod, "Even Better RNG", which replaces the game's RNG with XoShiRo128** (reason for choosing XoShiRo128** instead of a stronger algorithm was because it's optimized for 32-bit processing.)

If you need additional interfaces not available in XoshiroPRNG.Net but available in `MersenneTwister.cs`, you can point it out to me and I'll see what I can do.

**Comment by Sakorona** [comment]
Yeah, it is a bit of a convoluted license. (I use a NuGet implementation on another project). I'm on a bit of a Stardew Valley break for now but I'll remind myself to convert my PRNG object soon

**Comment by Sakorona** [comment]
Since I'm probably going to maintain the base assuming 32-bit users (for the time being), I'll likely use XoShiRo 128** in the next update, since I'm testing it on the other project atm.

Thank you for telling me about this!

**Comment by Sakorona** [comment]
Note to self: get this working

**Comment by Sakorona** [comment]
Updated! Thanks for reminding me. Will be syncing code later today.
